### ISSUE TITLE
Throws exception on optional serializables.

### ISSUE THREAD

**Issue by Jjastiny** [metova/Slim#2]
I have a fragment with serializable extra and even if I set it to optional, it still throws an exception.

**Comment by jrobinson3k1** [comment]
I know this is way late, but I'd need to see the stacktrace to figure out why it is throwing an exception. I'm closing this since it's pretty old. Sorry I didn't get to it at the time, the project was put on the back burner last Summer.

Feel free to reopen the issue if you have more information to share.
